#!/usr/bin/env sh
APP_DIR=/opt/terminex
SHORTCUT_DIR=$HOME/.local/share/applications
sudo cp -r "$(pwd)" /opt/
sudo chown -R $SUDO_USER:$SUDO_USER $APP_DIR
cd $APP_DIR
# Electron's version.
export npm_config_target=9.1.0
# The architecture of Electron, can be ia32 or x64.
export npm_config_arch=x64
export npm_config_target_arch=x64
# Download headers for Electron.
export npm_config_disturl=https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
export npm_config_runtime=electron
# Tell node-pre-gyp to build module from source code.
export npm_config_build_from_source=true
# Install all dependencies, and store cache to ~/.electron-gyp.

HOME=/home/$SUDO_USER/.electron-gyp npm install
sudo cp terminex /usr/bin/
sudo cp $APP_DIR/Terminex.desktop /usr/share/applications/

